"""
setup.py file for Wild Magic Python extension
"""

# Import native Python modules.
from distutils.core import setup, Extension, Command
import distutils
import inspect
import shutil
import os

# Import user configuration module.
import config


class Clean2(Command):
    """A more thorough clean command."""
    description = 'clean everything generated by a build* command'
    user_options = []
    def initialize_options(self):
        pass
    def finalize_options(self):
        pass
    def run(self):
        dont_erase = ('.svn'           ,
                      'config.py'      ,
                      'docs'           ,
                      'Makefile'       ,
                      'out'            ,
                      'README'         ,
                      'setup.py'       ,
                      'test.py'        ,
                      'tools'          ,
                      'wm5.i'          ,
                      )
        this_dir = os.path.dirname(inspect.getfile(inspect.currentframe()))
        this_dir = os.path.normpath(this_dir)
        for entry in os.listdir(this_dir):
            if entry in dont_erase:
                continue
            entry = os.path.join(this_dir, entry)
            print 'erasing', entry
            if os.path.isfile(entry):
                os.remove(entry)
            elif os.path.isdir(entry):
                shutil.rmtree(entry)

module = Extension(
    name         = '_wm5',
    sources      = ['wm5.i'],
    swig_opts    = ['-c++', '-I%s'%config.WM5INCDIR, '-cpperraswarn'],
    include_dirs = [config.WM5INCDIR],
    library_dirs = [config.WM5LIBDIR],
    libraries    = ['Wm5Mathematics', 'Wm5GlxGraphics',],
    )

setup(
    name         = 'wm5',
    version      = '0.1',
    description  = 'Python wrapper of Wild Magic libraries',
    author       = 'Velimir Mlaker',
    author_email = 'velimir dot mlaker at g mail dot com',
    ext_modules  = [module],
    py_modules   = ['wm5'],
    cmdclass     = { 'clean2' : Clean2 },
    )

# The end.
